# https://pre-commit.com/
# More hooks available at:
# https://pre-commit.com/hooks.html

# INSTALL ON MAC:
# brew install pre-commit

# INSTALL ON WINDOWS:
# pip install pre-commit

# INSTALL hooks for this workspace
# pre-commit install

exclude: '^modules/external/.*$'

repos:
# TERRAFORM
  # If running tf-docs it must be run first to avoid race condition relating to version constraints.
  # BUG: terraform_docs hook conflicts when used more than once.
  # Workaround with Python
  - repo: local
    hooks:
    - id: Terraform docs
      name: Terraform docs
      entry: python examples/terraform-docs.py
      language: system
      types: [python]
      always_run: true
      pass_filenames: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      # - id: terraform_docs
      #  args:
      #    - --args=--lockfile=false
      #    - --args=--config=.tfdocs-config.yml
      - id: terraform_fmt
      - id: terraform_validate
        # [^/]+: Exclude root module. Validation is done via examples/basic
        # see https://github.com/antonbabenko/pre-commit-terraform#terraform_validate
        exclude: |
            (?x)^(
                tests/.*|
                [^/]+|
            )$
      - id: terraform_tflint
        # Configure tflint by creating and updating the config file below.
        args: ['--args=--config=__GIT_WORKING_DIR__/.tflint.hcl']
      #-----------------------------------------
      # Moved to .github/.pre-commit-config.yaml
      #-----------------------------------------
      # - id: terraform_tfsec
      #   files: ^.*.tf$
      #   # Configure tfsec by creating and updating the config file below.
      #   args: ['--args=--config-file=__GIT_WORKING_DIR__/.tfsec-config.yml']
      # - id: terraform_checkov
      #   # Configure checkov by creating and updating the config file below.
      #   args: ['--args=--config-file __GIT_WORKING_DIR__/.checkov-config.yml']
# Python
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
# PRECOMMIT - GENERAL
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-case-conflict
      - id: check-json
        exclude: tsconfig.json|devcontainer.json
      # - id: pretty-format-json
      #   exclude: tsconfig.json|package-lock.json|package.json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
        args: ['--branch', 'develop', '--branch', 'main', '--branch', 'master']
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
    -   id: no-vanilla-readme
        name: Ensure README is updated
        entry: "example content; edit to suit your module"
        language: pygrep
        types: [text]
        files: README.md
