name: cleancode-python
on: [pull_request]

defaults:
  run:
    working-directory: ./lambda/app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ğŸ Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: ğŸ—ï¸ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==4.0.1
          pip install pytest==7.0.1
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: ğŸ‘©â€ğŸ« Lint with flake8
        run: |
          flake8 --count --max-complexity=10 --max-line-length=90 --statistics

      - name: ğŸ§ª Unit tests
        run: |
          pytest
