name: sam-publish
on: [publish]

defaults:
  run:
    working-directory: ./sam

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ğŸ Set up Python
        uses: actions/setup-python@v2

      - name: ğŸ¤– Set up SAM
        uses: aws-actions/setup-sam@v1

      - name: ğŸ¤ Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: ğŸ“¦ Package Application 
        run: |
          sam package \
          --template template.yaml \
          --s3-bucket aws-cat-clickops-main-deployment \
          --s3-prefix sam-package \
          --output-template-file packaged.yaml \
          --region eu-west-1

      - name: ğŸš€ Publish Application 
        run: |
          sam publish \
          -t packaged.yaml \
          --region eu-west-1